Ads 258
MetOffice/cdk_utils pull request #1
Opened 2021-06-14 10:08 UTC by jamesgreen-mo

Packaged up CDK utils inline with coding standards and made it pip installable.

2021-06-14 15:28 UTC, mo-emilyw approved these changes
Looks good - it might be worth discussing the pylint exclusions, but there aren't too many...

2021-06-15 10:28 UTC, crbunney requested changes
Looks good, some comments to address.

Also, src/cdkutils/_version.py seems to be an empty file on the PR? Which is odd

2021-06-15 10:28 UTC, crbunney commented on .github/workflows/coding-standards.yml
> +        lint_cmd: [isort, black, pylint, mypy, checkov]
Think we can get rid of checkov if there's no cloudformation in the repo

2021-06-15 10:28 UTC, crbunney commented on .github/workflows/push_to_artifactory.yml
> +          PASSWORD: ${{ secrets.ARTIFACTORY_APIKEY }}
These don't appear to be used, can they be removed?

2021-06-15 10:28 UTC, crbunney commented on .pylintrc
> +    F0010, # no init file
In general, when diverging from the standard set of excluded checks, I think it's better to disable the check in the specific place that's causing an issue with a comment that explains why it's ok. Documentation on how to do that is here: http://pylint.pycqa.org/en/latest/user_guide/message-control.html#block-disables

You can also use the check names rather than the numbers (from spitfire-template):
```
[MASTER]
disable=
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring
```

2021-06-15 10:28 UTC, crbunney commented on .pylintrc
> +    PylintIgnorePaths("venv", "tasks.py")
This isn't present in spitfire template, can it be removed?

2021-06-15 10:28 UTC, crbunney commented on pylint_ignore.py
> +from typing import Any, List, Tuple
This isn't present in spitfire template, can it be removed?

2021-06-15 10:28 UTC, crbunney commented on pyproject.toml
> +#    "--cov=cdkutils", # python package to cover, not directory, important for tox compatibility
Can we drop the commented out code please?

2021-06-15 10:28 UTC, crbunney commented on pyproject.toml
> +#]
This section isn't used either, can it be removed please?

2021-06-15 10:28 UTC, crbunney commented on setup.cfg
>  description =expected_parameter_keys  aws-utils library used to test aws infrastructure across all BG products
This needs updating

2021-06-15 10:28 UTC, crbunney commented on requirements/requirements-dev.txt
> +boto3==1.17.27
These are in the wrong place, they should be in the setup.cfg (which declares the packages dependencies). This file declares dependencies that are only used when developing

2021-06-15 10:28 UTC, crbunney commented on src/cdkutils/__init__.py
> +from src.cdkutils.cdk_utils import PipelineConfig
imports shouldn't contain the `src` dir as it's not part of the package
```suggestion
from .cdk_utils import PipelineConfig
```

2021-06-15 10:28 UTC, crbunney commented on tox.ini
> +    -Ur{toxinidir}/requirements/requirements-dev.txt
Dependencies that are required for running the tests should be pulled out of requirements-dev and listed here instead. requirements-dev.txt is meant for extra tooling required for setting up a dev environment (such as installing pre-commit and referencing the requirements-linting.txt file)

2021-06-16 12:55 UTC, mo-emilyw commented on .pylintrc
> +    R0903, # Too few public methods
Did you get a chance to look at these? I was hoping they could be excluded within the code that's triggering the errors instead of being excluded globally here?

2021-06-16 14:18 UTC, crbunney requested changes

2021-06-16 14:18 UTC, crbunney commented on pyproject.toml
> +[tool.coverage.paths]
Could you remove this section heading now we've got rid of the unused contents?

2021-06-16 14:18 UTC, crbunney commented on requirements/requirements-dev.txt
> +setuptools==54.1.2
Rather than maintaining 2 separate lists of  linting dependencies, it's better to reference the linting requirements file by adding a line that says `-r requirements-linting.txt`. In fact, I think everything here should be covered by either the test dependencies in tox or the linting requirements file?

2021-06-16 14:18 UTC, crbunney commented on requirements/requirements-linting.txt
> +invoke~=1.5.0
I think that all of these should be in the `setup.cfg` of `bginvoketasks` (although apparently they're not :( but a small PR would fix that)

So rather than repeating these dependencies in each project that uses bginvoketasks, we should put:
```
-r requirements-tox.txt
bginvoketasks~=0.0.2
```

2021-06-16 14:18 UTC, crbunney commented on setup.cfg
> +    boto3==1.17.27
Pinning dependencies in a library can cause dependency conflicts in the code that uses it (imagine you're working on code that uses 2 libraries, and each library has pinned its dependencies to different versions). For reusable libraries, it's best to declare a range of supported versions and leave the final decision on pinning to the end user (i.e. whoever is developing the code that makes use of this library)

```suggestion
    pygit2>=1.5.0
    aws-cdk.core>=1.107.0
    aws-cdk.pipelines>=1.107.0
    boto3>=1.17.27
```

2021-06-16 14:20 UTC, crbunney commented on src/cdkutils/cdk_utils.py
> +    # pylint: disable=too-many-instance-attributes:
👍🏻 yea, hard to avoid that in this case

2021-06-16 14:22 UTC, crbunney commented on src/cdkutils/cdk_utils.py
> +        # pylint: disable=no-self-use
I side with pylint on this one, the warning can be addressed by doing this
```suggestion
    @staticmethod
    def get_artifact_for_stack_output(pipeline: pipelines.CdkPipeline, output: core.CfnOutput) -> object:
```

2021-06-16 14:48 UTC, jamesgreen-mo commented on requirements/requirements-dev.txt
> +setuptools==54.1.2
Not all of them setuptools, twine and build are not referenced in linting or tox :)

2021-06-16 16:44 UTC, mo-emilyw approved these changes
Looks good, thanks for sticking with it! 👍🏽

2021-06-16 16:44 UTC, crbunney approved these changes
good stuff

2021-06-16 16:45 UTC, crbunney requested changes
almost forgot - _version.py is 0 bytes, when I'm pretty sure it should have some contents

2021-06-17 07:38 UTC, mo-emilyw approved these changes
Looks good 👍🏽

2021-06-17 08:07 UTC, crbunney approved these changes
All good to go!

2021-06-17 08:33 UTC, merged