[minor] ADS-410 allow updates to secrets on deploy
MetOffice/cdk_utils pull request #12
Opened 2021-07-27 15:41 UTC by jenniferriordan

2021-07-30 09:13 UTC, mo-emilyw requested changes
Looks good, just the request to reinstate the account id names :)

2021-07-30 09:13 UTC, mo-emilyw commented on src/cdkutils/config.py
> +        mgmt_acct_id: str,
Could we keep these as they were? This would require fairly extensive changes everywhere this library is used (currently these are accessed as pipeline_config.common.account_ids.mgmt for example which I think is quite clear)

2021-07-30 10:59 UTC, mo-emilyw approved these changes
Looks good 👍🏽

2021-07-30 14:40 UTC, AlisonWeir approved these changes
Approved, but you might want to update the bginvoketasks version a bit more.

2021-07-30 14:40 UTC, AlisonWeir commented on requirements/requirements-linting.txt
> +bginvoketasks~=0.0.7
There is a version 1.0.0 of bginvoketasks, which has the added safety and licence checking

2021-07-30 14:40 UTC, AlisonWeir commented on tooling.md
> +* linting:
If you do update to bginvoketasks 1.0.0, the safety and licence checking could be added here.

2021-08-02 07:45 UTC, mo-emilyw approved these changes

2021-08-02 07:47 UTC, AlisonWeir approved these changes

2021-08-02 07:52 UTC, merged