ADS-657: Create prereq KMS Stack
MetOffice/cdk_utils pull request #19
Opened 2021-08-31 16:11 UTC by jenniferriordan

Ticket link: https://metoffice.atlassian.net/browse/ADS-657

Checklist:
- [ ] Ensure commit message for merge contains major, minor, or patch

2021-08-31 16:37 UTC, mo-emilyw requested changes

2021-08-31 16:37 UTC, mo-emilyw commented on src/cdkutils/prereqs.py
> +            resources=["*"],
I think at least we should be able to limit resources to those with the right account id(s) in the arn - we would need to add these to the prereq stack deployment script though (as this will be deployed in different accounts) but hopefully we should be able to pull them through as a parameter. Although it could be tricky for s3 - maybe we should leave that out for now?

2021-08-31 16:51 UTC, jenniferriordan commented on src/cdkutils/prereqs.py
> +            resources=["*"],
I don't believe this relates to any account. It means attach this policy to this kms key. According to this (if I've interpreted it right): 
`Resource – (Required) In a key policy, the value of the Resource element is "*", which means "this KMS key." The asterisk ("*") identifies the KMS key to which the key policy is attached`
https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html

2021-09-02 09:08 UTC, mo-emilyw commented on src/cdkutils/prereqs.py
> +            resources=["*"],
Yes, sorry I was unclear - it was principals rather than resources I meant... in any case I think there are some things we need to discuss about where the key lives and how the policy works etc.

2021-09-02 15:22 UTC, mo-emilyw approved these changes

2021-09-02 15:30 UTC, AlisonWeir approved these changes

2021-09-02 16:05 UTC, AnnieBoucher approved these changes

2021-09-02 16:06 UTC, merged